services:
  - type: web
    name: aetherbot
    env: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production 